### ISSUE TITLE
Invalid Command

### ISSUE THREAD

**Issue by MajiSP** [Coffeelot/cw-vending#1]
With the latest update to QBCore - 

The TriggerEvent command:

('animations:client:EmoteCommandStart', {"dispenser"}) 
and
TriggerEvent('animations:client:EmoteCommandStart', {"damn"})

is no longer a valid command. Any fix?

**Comment by Coffeelot** [comment]
I have only heard problems with the latest QB-Core so I haven't bothered updating. Any errors you're getting that could help us see what the issues is?

**Comment by Randolio** [comment]
It just means you don't have the "dispenser" or "damn" emotes. I get the same error on the dispenser one because I don't have it. The "damn" one works fine :)
